SELECT DISTINCT codigo_oficina, ciudad FROM oficina;
SELECT DISTINCT telefono, ciudad FROM oficina WHERE pais = "España";
SELECT DISTINCT nombre,apellido1, apellido2, email FROM empleado WHERE codigo_jefe = "7";
SELECT DISTINCT puesto, nombre, apellido1, apellido2 FROM empleado WHERE codigo_jefe IS NULL;
SELECT DISTINCT nombre, apellido1, apellido2, puesto FROM empleado WHERE puesto <> "Representante Ventas";
SELECT DISTINCT nombre_cliente FROM cliente WHERE pais = "Spain";
SELECT DISTINCT estado FROM pedido;
SELECT DISTINCT fecha_pago FROM pago where YEAR(fecha_pago) = 2008;
SELECT DISTINCT fecha_pago FROM pago WHERE DATE_FORMAT(fecha_pago, '%Y') = '2008';
SELECT DISTINCT fecha_pago FROM pago WHERE fecha_pago >= '2008-01-01' AND fecha_pago < '2009-01-01';
SELECT DISTINCT codigo_pedido, codigo_cliente, fecha_esperada, fecha_entrega FROM pedido WHERE fecha_esperada < fecha_entrega;
SELECT DISTINCT codigo_pedido, codigo_cliente, fecha_esperada, fecha_entrega FROM pedido WHERE ADDDATE(fecha_entrega, INTERVAL +2 DAY) <= fecha_esperada;
SELECT DISTINCT codigo_pedido, codigo_cliente, fecha_esperada, fecha_entrega FROM pedido WHERE DATEDIFF(fecha_entrega, fecha_esperada ) <= -2;
SELECT DISTINCT * FROM pedido WHERE estado= "rechazado";
SELECT DISTINCT * FROM pedido WHERE MONTH(fecha_entrega)= 01 AND estado="entregado";
SELECT DISTINCT * from pago WHERE YEAR(fecha_pago)= 2008 AND forma_pago= "PayPal" ORDER BY total desc;
SELECT DISTINCT forma_pago FROM pago;
SELECT DISTINCT * FROM producto WHERE gama= "Ornamentales" AND cantidad_en_stock>100 ORDER BY  precio_venta DESC;
SELECT DISTINCT * FROM cliente WHERE ciudad="Madrid" AND (codigo_empleado_rep_ventas=11 OR codigo_empleado_rep_ventas=30);