/*
 * This source file was generated by the Gradle 'init' task
 */

/**
 * Clase principal de ejecución que sirve para testear la jerarquía de animales.
 * Se encarga de instanciar los diferentes objetos de las clases concretas y
 * mostrar sus atributos específicos por consola.
 * * @author BenjaminDTS
 * 
 * @version 1.0
 */
package composiciónmultiple;

public class App {
    /**
     * Método principal (punto de entrada) de la aplicación.
     * 
     * @param args Argumentos de la línea de comandos (no utilizados).
     */
    public static void main(String[] args) {
        // Instanciación de objetos de las clases concretas
        Coche coche1 = new Coche("Rojo", TipoCarroceria.Autoportante, TipoChasis.Independiente, 2000, "Michelin", 17,
                215, 60);

        Coche coche2 = new Coche("Azul", TipoCarroceria.Autoportante, TipoChasis.Monocasco, 2500, "Pirelli", 18, 225,
                65);

        // Visualización de datos del coche1 y coche2
        Coche.imprimirCoche(coche1);
        Coche.imprimirCoche(coche2);
    }

}
