CREATE TABLE ZONAS 
    (Letra VARCHAR2(1), 
    Profundidad NUMBER (4), 
    Anchura NUMBER(5,2),
    NumBarcos NUMBER,
    TipoBarcos VARCHAR2(30));

CREATE TABLE ejerccio_oracle (
ID NUMBER (7) PRIMARY KEY,
NAME VARCHAR2 (25)
);

DESCRIBE EJERCCIO_ORACLE;

DROP TABLE  EJERCICIO_ORACLE;
