/*
 * This source file was generated by the Gradle 'init' task
 */
package asignatura;

public class App {
    public static void main(String[] args) {
        // Crear un objeto Asignatura
        Asignatura poo = new Asignatura(4100547, 4, "Programación Orientada a Objetos");

        // Escribir el objeto en un archivo
        String archivo = "asignatura.dat";
        poo.escribirAsignatura(archivo);

        // Leer el objeto desde el archivo
        Asignatura asignaturaLeida = Asignatura.leerAsignatura(archivo);
        if (asignaturaLeida != null) {
            asignaturaLeida.imprimir();
        }
    }
}
