/*
 * This source file was generated by the Gradle 'init' task
 */
package checkarray;

import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Introduce el tamaño del array: ");
        String[] strings = new String[sc.nextInt()];
        for (int i = 0; i < strings.length; i++) {
            System.out.println("Introduce el valor de la posición " + i + ": ");
            strings[i] = sc.next();
        }
        System.out.println("Introduce la letra a buscar: ");
        char letra = sc.next().charAt(0);
        for ( String string : strings) {
            if (string.charAt(0) == letra) {
                System.out.println(string +  " empieza por " + letra);
            }  
                
            
            sc.close();
        }
    }
}
