/*
 * This source file was generated by the Gradle 'init' task
 */
package composiciónmultiple;


public class App {


    public static void main(String[] args) {
        Coche coche1 = new Coche("Rojo", TipoCarroceria.Autoportante, TipoChasis.Independiente, 2000, "Michelin", 17, 215, 60);
        
        Coche coche2 = new Coche("Azul", TipoCarroceria.Autoportante, TipoChasis.Monocasco, 2500, "Pirelli", 18, 225, 65);
        
        ImprimirCoche(coche1);
        ImprimirCoche(coche2);
    }
    
}
