/*
 * This source file was generated by the Gradle 'init' task
 */
package composicionpmultiples;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        Biblioteca biblioteca = new Biblioteca("Biblioteca Nacional", new ArrayList<Libros>());
        Libros libro1 = new Libros("El Quijote", "Miguel de Cervantes", 1605, "Francisco de Robles", "Cervantes, M. (1605). El Quijote. Francisco de Robles.");
        Libros libro2 = new Libros("La Odisea", "Homero", 800, "Desconocida", "Homero. (800). La Odisea. Desconocida.");   
        Libros libro3 = new Libros("La Iliada", "Homero", 800, "Desconocida", "Homero. (800). La Iliada. Desconocida.");
        Libros libro4 = new Libros("El Aleph", "Jorge Luis Borges", 1949, "Sur", "Borges, J. L. (1949). El Aleph. Sur.");
        Libros libro5 = new Libros("Cien años de soledad", "Gabriel García Márquez", 1967, "Sudamericana", "García Márquez, G. (1967). Cien años de soledad. Sudamericana.");
        Biblioteca.añadirLibro(biblioteca.getLibros(), libro1);
        Biblioteca.añadirLibro(biblioteca.getLibros(), libro2);
        Biblioteca.añadirLibro(biblioteca.getLibros(), libro3);
        Biblioteca.añadirLibro(biblioteca.getLibros(), libro4);
        Biblioteca.añadirLibro(biblioteca.getLibros(), libro5);
        Biblioteca.listarLibros(biblioteca.getLibros());
    }
}
